### ISSUE TITLE
Peer-to-Peer Review

### ISSUE THREAD

**Issue by ishimwepati** [Uzair-Manzoor/Portfolio#16]

**Comment by ishimwepati** [comment]
Wow, so far so good, nice codes dear, Keep it up.

**Optional:** You used a lot of Pixels in CSS while PIxels are static kindly use % if possible to allow your design to look nice on all screens.

**Comment by bhushan354** [comment]
great , nice job so far 👍  , but i suggest some changes :
- your page is having horizontal scrolling , horizontal scrolling will make your portfolio site look unprofessional .
- in order to solve this try adding *{ border : 1px solid red;} to your code and debug the issue.

cheers!!

**Comment by Uzair-Manzoor** [comment]
well I never knew that we can fix horizontal scrolling in a professional way by applying a border
